[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CardiacG2P"
authors = [{name = "Kat J.", email = "k.josephs@imperial.ac.uk"}]
dynamic = ["version", "description"]
